# Generated by Django 3.2.25 on 2024-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='Description')),
                ('numOfReads', models.IntegerField(db_column='# of reads (unnormalized)')),
                ('sampleSource', models.TextField(db_column='Sample Name')),
            ],
        ),
        migrations.CreateModel(
            name='SampleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnknownMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levDistance', models.TextField(db_column='Levenshtein Distance Category')),
                ('type', models.TextField(db_column='Type')),
                ('numOfReads', models.IntegerField(db_column='# of reads (unnormalized)')),
                ('sampleSource', models.TextField(db_column='Sample Name')),
            ],
        ),
    ]
