# Generated by Django 3.2.25 on 2024-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesource',
            name='name',
            field=models.TextField(db_column='name'),
        ),
    ]
